# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UploadApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UploadApp

  target 'UploadAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UploadAppUITests' do
    # Pods for testing
  end

  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  pod 'Firebase/RemoteConfig'

end
